services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8082:5432
    volumes:
      - chat-app-postgres:/var/lib/postgresql/data
volumes:
  chat-app-postgres:
